# coding: utf-8

"""
    Toptout

    Get data about telemetry channels in various applications  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Value(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'opt_out': 'str',
        'opt_in': 'str'
    }

    attribute_map = {
        'opt_out': 'opt_out',
        'opt_in': 'opt_in'
    }

    def __init__(self, opt_out=None, opt_in=None):  # noqa: E501
        """Value - a model defined in Swagger"""  # noqa: E501
        self._opt_out = None
        self._opt_in = None
        self.discriminator = None
        self.opt_out = opt_out
        self.opt_in = opt_in

    @property
    def opt_out(self):
        """Gets the opt_out of this Value.  # noqa: E501


        :return: The opt_out of this Value.  # noqa: E501
        :rtype: str
        """
        return self._opt_out

    @opt_out.setter
    def opt_out(self, opt_out):
        """Sets the opt_out of this Value.


        :param opt_out: The opt_out of this Value.  # noqa: E501
        :type: str
        """
        if opt_out is None:
            raise ValueError("Invalid value for `opt_out`, must not be `None`")  # noqa: E501

        self._opt_out = opt_out

    @property
    def opt_in(self):
        """Gets the opt_in of this Value.  # noqa: E501


        :return: The opt_in of this Value.  # noqa: E501
        :rtype: str
        """
        return self._opt_in

    @opt_in.setter
    def opt_in(self, opt_in):
        """Sets the opt_in of this Value.


        :param opt_in: The opt_in of this Value.  # noqa: E501
        :type: str
        """
        #if opt_in is None:
        #    raise ValueError("Invalid value for `opt_in`, must not be `None`")  # noqa: E501

        self._opt_in = opt_in

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Value, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Value):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
