/* 
 * Toptout
 *
 * Get data about telemetry channels in various applications
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Value
    /// </summary>
    [DataContract]
        public partial class Value :  IEquatable<Value>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Value" /> class.
        /// </summary>
        /// <param name="optOut">optOut (required).</param>
        /// <param name="optIn">optIn (required).</param>
        public Value(string optOut = default(string), string optIn = default(string))
        {
            this.OptOut = optOut;
            this.OptIn = optIn;
        }
        
        /// <summary>
        /// Gets or Sets OptOut
        /// </summary>
        [DataMember(Name="opt_out", EmitDefaultValue=false)]
        public string OptOut { get; set; }

        /// <summary>
        /// Gets or Sets OptIn
        /// </summary>
        [DataMember(Name="opt_in", EmitDefaultValue=false)]
        public string OptIn { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Value {\n");
            sb.Append("  OptOut: ").Append(OptOut).Append("\n");
            sb.Append("  OptIn: ").Append(OptIn).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as Value);
        }

        /// <summary>
        /// Returns true if Value instances are equal
        /// </summary>
        /// <param name="input">Instance of Value to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Value input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.OptOut == input.OptOut ||
                    (this.OptOut != null &&
                    this.OptOut.Equals(input.OptOut))
                ) && 
                (
                    this.OptIn == input.OptIn ||
                    (this.OptIn != null &&
                    this.OptIn.Equals(input.OptIn))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.OptOut != null)
                    hashCode = hashCode * 59 + this.OptOut.GetHashCode();
                if (this.OptIn != null)
                    hashCode = hashCode * 59 + this.OptIn.GetHashCode();
                return hashCode;
            }
        }
    }
}
